spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/mainproject?serverTimezone=Asia/Seoul
    password: 1234
  jpa:
    properties:
      hibernate:
        format_sql: 'true'
        show_sql: 'true'
    database-platform: org.hibernate.dialect.MySQL57InnoDBDialect
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
          kakao:
            client-id: 3713566f240a38a563fdcf1c6fbe54dd
            client-secret: tgDSN8xQe4wjGpnPUW0FayEO6es3UVer
            client-name: Kakao
            authorization-grant-type: authorization_code
            redirect-uri: "http://localhost:8000/oauth2/authorization/kakao"
            scope:
              - profile_nickname
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me


jwt:
  key: ${JWT_SECRET_KEY}
  access-token-expiration-minutes: 30
  refresh-token-expiration-minutes: 420

mail:
  address:
    admin: rjf654@gmail.com

